version: '3.0'
services:
  app:
    build: .
    ports: 
      - 80:80
    environment:
      APP_ENV: local
      APP_PORT: 80
      DB_DSN: root:password@tcp(go_mysql)/local
    networks:
      - backend
      - frontend
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: go_mysql
    image: mysql:8.0
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
networks:
  backend:
    external: true
  frontend:
    external: true
