version: '3.0'
services:
  app:
    build: .
    ports: 
     - 80:80
    networks:
      - backend
      - frontend
    volumes:
      - .:/app
networks:
  backend:
    external: true
  frontend:
    external: true
